pipeline:
  build:
    image: plugins/docker
    repo: kradalby/netboxxx
    secrets: [ docker_username, docker_password ]
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
    when: 
        branch: master

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: netboxxx-deployment
    repo: kradalby/netboxxx
    container: netboxxx-container
    namespace: netboxxx
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
      - ${DRONE_COMMIT_SHA:0:8}

  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
